//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Resources
{
    using System;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Main
    {
        
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Main()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Main", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Confirm Email.
        /// </summary>
        internal static string ConfirmEmail
        {
            get
            {
                return ResourceManager.GetString("ConfirmEmail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string ConfirmPassword
        {
            get
            {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create Account.
        /// </summary>
        internal static string CreateAccount
        {
            get
            {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Email .
        /// </summary>
        internal static string Email
        {
            get
            {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string FirstName
        {
            get
            {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &amp;copy Copyright 2014 Majorsilence Solutions Inc..
        /// </summary>
        internal static string FooterCopR
        {
            get
            {
                return ResourceManager.GetString("FooterCopR", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to follow us.
        /// </summary>
        internal static string FooterFollowUs
        {
            get
            {
                return ResourceManager.GetString("FooterFollowUs", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to language.
        /// </summary>
        internal static string FooterLang
        {
            get
            {
                return ResourceManager.GetString("FooterLang", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        internal static string FooterPPolicy
        {
            get
            {
                return ResourceManager.GetString("FooterPPolicy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pricing.
        /// </summary>
        internal static string FooterPrice
        {
            get
            {
                return ResourceManager.GetString("FooterPrice", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Terms of Service.
        /// </summary>
        internal static string FooterTos
        {
            get
            {
                return ResourceManager.GetString("FooterTos", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        internal static string ForgotPassword
        {
            get
            {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string LastName
        {
            get
            {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        internal static string MenuAboutUs
        {
            get
            {
                return ResourceManager.GetString("MenuAboutUs", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string MenuLogin
        {
            get
            {
                return ResourceManager.GetString("MenuLogin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string MenuAccount
        {
            get
            {
                return ResourceManager.GetString("MenuAccount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string MenuLogout
        {
            get
            {
                return ResourceManager.GetString("MenuLogout", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string MenuServices
        {
            get
            {
                return ResourceManager.GetString("MenuServices", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        internal static string MenuSetup
        {
            get
            {
                return ResourceManager.GetString("MenuSetup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string MenuSignUp
        {
            get
            {
                return ResourceManager.GetString("MenuSignUp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password
        {
            get
            {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Submit
        {
            get
            {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
    }
}
