using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Majorsilence.Vpn.Logic.Accounts;

/// <summary>
/// For use with UserDetails class.
/// </summary>
public class UserServerDetailsInfo
{
    public int RegionId { get; set; }

    public string RegionName { get; set; }

    public int VpnServerId { get; set; }

    public string VpnServerName { get; set; }

    public string Address { get; set; }

    /// <summary>
    /// Autogenerated per account and is saved in plain text
    /// </summary>
    /// <value>The pptp password.</value>
    public string PptpPassword { get; set; }
}